#1st august 2026
/*5. Implement an OpenMP program to generate an array
 of random integers using the single construct. Then use
 the parallel for directive to compute the square of each
 element. Display the Thread ID that generates the array and 
 the Thread IDs processing the elements.*/
#include <stdio.h>
#include <stdlib.h>
#include <omp.h>

int main() {
    int N;
    printf("Enter the size of the array: ");
    scanf("%d", &N);
    int arr[N];
    #pragma omp parallel
    {
        #pragma omp single
        {
            printf("Array generated by Thread ID: %d\n", omp_get_thread_num());
            for(int i = 0; i < N; i++) {
                arr[i] = rand() % 10;
            }
        }

        #pragma omp for
        for(int i = 0; i < N; i++) {
            printf("Thread ID %d processed index %d: %d^2 = %d\n", 
                    omp_get_thread_num(), i, arr[i], arr[i] * arr[i]);
        }
    }

    return 0;
}
